# Global options
[mypy]

# Make def annotations mandatory
disallow_untyped_defs = True

# Prevent errors coming from 3rd party libraries
ignore_missing_imports = True

warn_return_any = False
warn_unused_configs = True
follow_imports = skip

# Force color output
color_output = True
